# Generated by Django 5.1 on 2024-11-18 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Objetivos Generales',
            },
        ),
        migrations.CreateModel(
            name='ModelAnteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anteproyecto', models.CharField(max_length=200)),
                ('nombre_integrante1', models.CharField(max_length=50)),
                ('nombre_integrante2', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=5000, null=True)),
                ('carta_presentacion', models.BinaryField(blank=True, null=True)),
                ('anteproyecto', models.BinaryField(blank=True, null=True)),
                ('director', models.CharField(max_length=50, null=True)),
                ('codirector', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('solicitud_enviada', models.BooleanField(blank=True, null=True)),
                ('estado', models.BooleanField(default=False)),
                ('documento_radicado', models.BinaryField(blank=True, null=True)),
                ('documento_concepto', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Anteproyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Anteproyectos',
            },
        ),
        migrations.CreateModel(
            name='ModelObjetivosEspecificos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_observacion', models.DateTimeField(blank=True, null=True)),
                ('documento_avance', models.BinaryField(blank=True, null=True)),
                ('documento_correcciones', models.BinaryField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=False)),
                ('objetivo_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='estudiante.modelobjetivogeneral')),
            ],
            options={
                'verbose_name_plural': 'Objetivos especificos',
            },
        ),
        migrations.CreateModel(
            name='ModelActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('objetivo_general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='estudiante.modelobjetivogeneral')),
                ('objetivos_especificos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='estudiante.modelobjetivosespecificos')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ModelProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_final', models.BinaryField(blank=True, null=True)),
                ('carta_presentacion_final', models.BinaryField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('solicitud_enviada', models.BooleanField(blank=True, default=False, null=True)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('documento_radicado', models.BinaryField(blank=True, null=True)),
                ('documento_concepto', models.BinaryField(blank=True, null=True)),
                ('anteproyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proyecto_Final', to='estudiante.modelanteproyecto')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proyecto_Final', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proyectos Finales',
            },
        ),
        migrations.AddField(
            model_name='modelobjetivogeneral',
            name='proyecto_final',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_general', to='estudiante.modelproyectofinal'),
        ),
        migrations.CreateModel(
            name='ModelFechasProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_etapa_uno', models.DateField(blank=True, null=True)),
                ('fecha_etapa_dos', models.DateField(blank=True, null=True)),
                ('fecha_etapa_tres', models.DateField(blank=True, null=True)),
                ('fecha_etapa_cuatro', models.DateField(blank=True, null=True)),
                ('fecha_etapa_cinco', models.DateField(blank=True, null=True)),
                ('fecha_etapa_seis', models.DateField(blank=True, null=True)),
                ('fecha_sustentacion', models.DateTimeField(blank=True, null=True)),
                ('proyecto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='estudiante.modelproyectofinal')),
            ],
            options={
                'verbose_name_plural': 'Fechas de proyectos',
            },
        ),
        migrations.CreateModel(
            name='ModelAsignacionJurados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jurado', models.CharField(max_length=50)),
                ('fecha_sustentacion', models.DateField()),
                ('proyecto_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jurados', to='estudiante.modelproyectofinal')),
            ],
            options={
                'verbose_name_plural': 'Jurados Asignados',
            },
        ),
    ]
