# Generated by Django 5.1 on 2024-11-18 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluacionAnteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('doc_evaluacion_anteproyecto', models.BinaryField(blank=True, null=True)),
                ('anteproyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_anteproyectos', to='estudiante.modelanteproyecto')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_anteproyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones de Anteproyectos',
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluacionProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('doc_evaluacion_proyecto', models.BinaryField(blank=True, null=True)),
                ('jurado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos', to=settings.AUTH_USER_MODEL)),
                ('proyecto_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_proyectos', to='estudiante.modelproyectofinal')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones de Proyectos Finales',
            },
        ),
    ]
